#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     touchsnsr,      sensorTouch)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motor1,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motor2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     spnmtr,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     lftmtr,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Setup Motors^

//========================================//
//This TeleOp code allows for driving the //
//robot using the Y axis of ONE controller//
//thingy. Can be used with samantha or    //
//wired directly.                         //
//========================================//

//Allow Use Of Joysticks:
#pragma  debuggerWindows("joystickSimple");
#include "JoystickDriver.c"

//Define Constants:
const int THRESHOLD  =10;
const int SPEED_MULT =1 ;
const int SPIN_SPEED =75;
const int LIFT_SPEED =100;

//Main Code:
task main(){
	while(true){ //Repeat the following forever:
		{
			if(abs(SPEED_MULT * joystick.joy1_y1) > THRESHOLD) { //If the joystick is outside of the deadzone:
				motor[motor1] = SPEED_MULT * joystick.joy1_y1;   //Set motor speed to joystick value * multiplier
			}else{                                               //Otherwise:
				motor[motor1] = 0;                               //Set motor to 0
			}
			if(abs(SPEED_MULT * joystick.joy1_y2) > THRESHOLD) { //If the joystick is outside of the deadzone:
				motor[motor2] = SPEED_MULT * joystick.joy1_y2;   //Set motor speed to joystick value * multiplier
			}else{                                               //Otherwise:
				motor[motor2] = 0;                               //Set motor to 0
			}
		}
		{
			if(joy1Btn(0)==1){
				motor[spnmtr]=SPIN_SPEED;
			}else{
				motor[spnmtr]=0;
			}
			if(joy1Btn(1)==1){
				motor[lftmtr]=LIFT_SPEED;
			}else{
				if(joy1Btn(2)==1){
					motor[lftmtr]=-LIFT_SPEED;
				}else{
					motor[lftmtr]=0;
				}
			}
		}
	}
}
